Fixed #465: trigger docker publisgh on release
kiwix/kiwix-build pull request #467
Opened 2021-01-11 12:07 UTC by rgaudin

This triggers a `workflow_dispatch` event on the `docker.yml` workflow or the matching
repository for both `zim-tools` and `kiwix-tools` targets that supports it.

@mgautierfr this uses requests as requests is already used in upload_bintray and thus installed in the images used. I had a version using only urllib if you'd prefer.

Also, this is based on the filtering that is already done in the matrix and earlier in the script so it's just triggered after the upload of the binaries but that may not be obvious.

Finally, this just prints on error ; should we raise/fail? How critical is this given it can be triggered manually…

2021-01-11 12:21 UTC, kelson42 approved these changes

2021-01-13 15:00 UTC, mgautierfr requested changes
> @mgautierfr this uses requests as requests is already used in upload_bintray and thus installed in the images used. I had a version using only urllib if you'd prefer.
> Also, this is based on the filtering that is already done in the matrix and earlier in the script so it's just triggered after the upload of the binaries but that may not be obvious.

We're good here.

> Finally, this just prints on error ; should we raise/fail? How critical is this given it can be triggered manually…

We should fail. If not we may assume that everything is fine and  we will not trigger manually. (I'm pretty sure that I will not check that docker workflow is correctly run if CI tell me no error)

(I haven't check that the url/header/json is good. I'm assuming that it is adapted to what docker workflow expects.)

2021-01-13 15:20 UTC, rgaudin commented
Thanks ; updated it accordingly. Yes json and headers are appropriate and has been manually tested.

2021-01-13 15:42 UTC, mgautierfr commented
We are good. Can you squash your commits ? (There is no need to have the history of your "wrong" attempts)

---

Appveyor is failing for something else, I'm on it.

2021-01-13 16:41 UTC, mgautierfr approved these changes

2021-01-13 16:42 UTC, merged