CoreKiwix for iOS Simulator
kiwix/kiwix-build pull request #668
Opened 2023-12-04 11:17 UTC by rgaudin

When we introduced CoreKiwix.xcframework, we made two mistakes:

- We forgot that some devs are on Apple Silicon and did not include arm64 arch for simulator
- We kept the `x86_64-apple-ios` target thinking simulator is a “just” an iOS on x64

This target mistake prevented XCode from finding our lib usable with the Simulator on x64. Not including an arm64 version obviously prevented Silicon-using devs from using the Simulator.

The included libs changes now from

| Name                         | Content                                               |
| ---------------------------- | ----------------------------------------------------- |
| `ios-arm64`                  | All iOS devices are arm64                             |
| `ios-x86_64-simulator`       | Single x64 binary for Simulator                       |
| `macos-arm64_x86_64`         | Fat binary for macOS with both x64 and arm64          |

To

| Name                         | Content                                               |
| ---------------------------- | ----------------------------------------------------- |
| `ios-arm64`                  | All iOS devices are arm64                             |
| `ios-arm64_x86_64-simulator` | Fsat binary for iOS Simulator with both x64 and arm64 |
| `macos-arm64_x86_64`         | Fat binary for macOS with both x64 and arm64          |

## Changes

- `iOSx64` Platforn renamed to `iOSx64Simulator` with its target fixed to `x86-apple-ios-simulator` (was `x86_64-apple-ios`)
- Added platformn `iOSArm64Simulator` for Apple Silicon devs to run Simulator
- `AppleXCFramework` dependency gets two changes: - Depends on all those platforms - `_make_macos_fat()` turned generic and called both for macOS fat binary and iOS Simulator one

Fixes #667

**Note**: this may require a new build of the libkiwix 13.0.0 release. @kelson42 WDYT?

2023-12-04 13:21 UTC, rgaudin commented
OK will do ; recreating base deps 95 now as it doesn't include the new names

2023-12-04 15:08 UTC, mgautierfr requested changes

2023-12-04 15:46 UTC, rgaudin commented on kiwixbuild/dependencies/apple_xcframework.py
>                  run_command(command, lib_dir, context)
Ah looks like `--continue` without `add`! Thanks for spotting it. Testing before repushing

2023-12-05 07:05 UTC, rgaudin commented
OK it's now all green ; pushing again to resolve the fixup. We're good to merge

2023-12-05 08:46 UTC, mgautierfr commented
The today nightly has failed on macos apple_all_static (https://github.com/kiwix/kiwix-build/actions/runs/7094928431/job/19311027499).
It is potentially related to this PR which may (if you have deleted them) have recreate `base_deps2_*` archives.

2023-12-05 09:19 UTC, rgaudin commented
> The today nightly has failed on macos apple_all_static (https://github.com/kiwix/kiwix-build/actions/runs/7094928431/job/19311027499). It is potentially related to this PR which may (if you have deleted them) have recreate `base_deps2_*` archives.

That's expected. I had to delete 96 and recreate it (in this PR) so it includes the new name. As you can see in the log, it lacks `BUILD_iOS_x86_64` which is the former name of the `iOSSimulator_x86_64` platform-target

2023-12-05 10:07 UTC, mgautierfr approved these changes

2023-12-05 10:09 UTC, mgautierfr commented
Would have been better to change the base_deps_version to 97 to avoid such conflict (for the next time).
But we are good. I'm merging.

2023-12-05 10:09 UTC, merged